name: Lint

on:
  # Run on pushes to select branches and on all pull requests.
  push:
    branches:
      - master
      - trunk
      - 'release/**'
      - 'hotfix/[0-9]+.[0-9]+*'
      - 'feature/**'
  pull_request:
  # Allow manually triggering the workflow.
  workflow_dispatch:

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Lint against the highest/lowest supported versions of each PHP major.
        # And also do a run against "nightly" (the current dev version of PHP).
        php_version: ['5.6', '7.0', '7.4', '8.0', '8.1', '8.2']

    name: "Lint: PHP ${{ matrix.php_version }}"

    # Allow builds to fail on as-of-yet unreleased PHP versions.
    continue-on-error: ${{ matrix.php_version == '8.2' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # The prefix-dependencies task only works on PHP 7.2 (and higher) and we need to prefix
      # the dependencies which are included in the distributed code to make sure there
      # are no parse errors in the adjusted code.
      - name: Install PHP 7.x for generating the vendor_prefixed directory
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.2
          coverage: none

      - name: Install Composer dependencies and generate vendor_prefixed directory
        uses: ramsey/composer-install@v2

      # Moving the necessary tools to no-dev prevents dependency hell due to the lock file containing
      # packages locked at versions incompatible with the full range of supported PHP versions.
      # This move needs to happen while still on PHP 7.2 as otherwise Composer will reject it.
      - name: Move the linting tools from dev to no-dev
        run: composer require yoast/yoastcs --no-scripts

      - name: Remove the vendor directory
        run: rm -rf vendor/*

      - name: Install PHP for the actual linting
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          ini-values: zend.assertions=1, error_reporting=-1, display_errors=On
          coverage: none
          tools: cs2pr

      # Install dependencies and handle caching in one go.
      # @link https://github.com/marketplace/actions/install-composer-dependencies
      - name: "Install Composer dependencies (lint tools and no-dev only)"
        uses: ramsey/composer-install@v2
        with:
          composer-options: "--no-dev --no-scripts"

      - name: Lint against parse errors
        run: composer lint -- --checkstyle | cs2pr
